---
apiVersion: eks.sarathy.io/v1beta1
kind: EKSCluster
metadata:
  name: crossplane-prod-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parameters:
    region: eu-west-3
    vpc-name: "crossplane-vpc-only"
    vpc-cidrBlock: "10.20.0.0/16"

    subnet1-public-name: "public-worker-1 "
    subnet1-public-cidrBlock: "10.20.1.0/28"
    subnet1-public-availabilityZone: "eu-west-3a"

    subnet2-public-name: "public-worker-2"
    subnet2-public-cidrBlock: "10.20.2.0/28"
    subnet2-public-availabilityZone: "eu-west-3b"

    subnet1-private-name: "private-worker-1 "
    subnet1-private-cidrBlock: "10.20.11.0/28"
    subnet1-private-availabilityZone: "eu-west-3a"

    subnet2-private-name: "private-worker-2"
    subnet2-private-cidrBlock: "10.20.12.0/28"
    subnet2-private-availabilityZone: "eu-west-3b"

    subnet-db1-private-name: "private-db-1 "
    subnet-db1-private-cidrBlock: "10.20.21.0/28"
    subnet-db1-private-availabilityZone: "eu-west-3a"

    subnet-db2-private-name: "private-db-2"
    subnet-db2-private-cidrBlock: "10.20.22.0/28"
    subnet-db2-private-availabilityZone: "eu-west-3b"

    cluster-role: arn:aws:iam::187967886115:role/EKSClusterRole-eksClusterRole-1FR2I6UISHIZN
    workernode-role: arn:aws:iam::187967886115:role/EKS-WorkerNode-Role

    k8s-version: "1.21"
    workload-type: "non-gpu"
    workers-size: 1

  compositionRef:
    name: amazon-eks-cluster

  writeConnectionSecretToRef:
    namespace: eks
    name: crossplane-prod-cluster-connection
